# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.Album')),
            ],
        ),
    ]
