# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.Artist')),
            ],
        ),
    ]
